{{- if and .Values.db.enabled .Values.db.internal.persistence.enabled (not .Values.db.internal.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "clientvault.fullname" . }}-db
  namespace: {{ include "clientvault.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "clientvault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: db
spec:
  accessModes:
{{ toYaml .Values.db.internal.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.db.internal.persistence.size }}
  {{- if .Values.db.internal.persistence.storageClass }}
  storageClassName: {{ .Values.db.internal.persistence.storageClass }}
  {{- end }}
{{- end }}
