{{- if .Values.secrets.tokens.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.tokens.name | default "tokens" }}
  namespace: {{ include "clientvault.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "clientvault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: tokens
stringData:
  accessToken: {{ include "clientvault.secret.tokens.access" . | quote }}
{{- end }}
