{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clientvault.fullname" . }}-server
  namespace: {{ include "clientvault.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "clientvault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: {{ include "clientvault.name" . }}
    app.kubernetes.io/component: server
  ports:
    - name: http-tcp
      port: {{ .Values.server.service.port }}
      targetPort: {{ include "clientvault.server.containerPort" . }}
      protocol: TCP
{{- end }}
