{{- if .Values.redisInternal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clientvault.fullname" . }}-redis
  namespace: {{ include "clientvault.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "clientvault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "clientvault.name" . }}
    app.kubernetes.io/component: redis
  ports:
    - port: {{ .Values.redisInternal.service.port }}
      targetPort: {{ .Values.redisInternal.service.port }}
      protocol: TCP
      name: redis
{{- end }}
