apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clientvaultcrm-db-pvc
  namespace: clientvaultcrm
spec:
  storageClassName: default
  volumeName: clientvaultcrm-db-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
