apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clientvaultcrm-docker-data-pvc
  namespace: clientvaultcrm
spec:
  storageClassName: default
  volumeName: clientvaultcrm-docker-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
